// <auto-generated />
using InfoCity.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfoCity.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("InfoCity.API.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CityId");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Description = "Bogota es la capital de Colombia.",
                            Name = "Bogota"
                        },
                        new
                        {
                            CityId = 2,
                            Description = "Medellin es una ciudad vibrante y llena de cultura, rodeada de montañas y conocida por su clima agradable.",
                            Name = "Medellin"
                        },
                        new
                        {
                            CityId = 3,
                            Description = "Cali, conocida como la capital de la salsa, es una ciudad llena de ritmo, alegría y tradiciones colombianas.",
                            Name = "Cali"
                        },
                        new
                        {
                            CityId = 4,
                            Description = "Barranquilla es una ciudad costera con una mezcla única de culturas, famosa por su carnaval colorido y animado.",
                            Name = "Barranquilla"
                        },
                        new
                        {
                            CityId = 5,
                            Description = "Cartagena es una ciudad histórica con impresionantes fortificaciones y playas de aguas cristalinas.",
                            Name = "Cartagena"
                        },
                        new
                        {
                            CityId = 6,
                            Description = "Santa Marta es una joya costera con hermosos paisajes naturales, incluyendo la majestuosa Sierra Nevada de Santa Marta.",
                            Name = "Santa Marta"
                        },
                        new
                        {
                            CityId = 7,
                            Description = "Manizales es una ciudad ubicada en la zona cafetera de Colombia, rodeada de verdes montañas y con un clima agradable.",
                            Name = "Manizales"
                        },
                        new
                        {
                            CityId = 8,
                            Description = "Pereira es una ciudad dinámica y moderna, conocida por ser parte del Eje Cafetero y sus extensos paisajes verdes.",
                            Name = "Pereira"
                        },
                        new
                        {
                            CityId = 9,
                            Description = "Pasto es una ciudad andina con una rica herencia cultural y tradiciones ancestrales arraigadas en su identidad.",
                            Name = "Pasto"
                        },
                        new
                        {
                            CityId = 10,
                            Description = "Ibagué es conocida como la 'Ciudad Musical de Colombia' y es famosa por su folclore y festivales musicales.",
                            Name = "Ibagué"
                        },
                        new
                        {
                            CityId = 11,
                            Description = "Neiva es una ciudad cálida y acogedora, ubicada en la región del Huila, con bellos paisajes y cultura cafetera.",
                            Name = "Neiva"
                        });
                });

            modelBuilder.Entity("InfoCity.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("PointInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PointInterestId");

                    b.HasIndex("CityId");

                    b.ToTable("pointOfInterests");

                    b.HasData(
                        new
                        {
                            PointInterestId = 1,
                            CityId = 1,
                            Description = "Monserrate ofrece una vista panorámica impresionante de Bogotá y es un lugar sagrado de peregrinación.",
                            Name = "Monserrate"
                        },
                        new
                        {
                            PointInterestId = 2,
                            CityId = 2,
                            Description = "El Parque Arví es un oasis natural cerca de Medellín, ideal para caminatas, ecoturismo y experiencias al aire libre.",
                            Name = "Parque Arví"
                        },
                        new
                        {
                            PointInterestId = 3,
                            CityId = 3,
                            Description = "El Cristo Rey es una majestuosa estatua ubicada en una colina, que ofrece una vista panorámica de la ciudad de Cali.",
                            Name = "Cristo Rey"
                        },
                        new
                        {
                            PointInterestId = 4,
                            CityId = 4,
                            Description = "La Casa del Carnaval es un lugar interactivo que muestra la historia y la tradición del carnaval barranquillero.",
                            Name = "Casa del Carnaval"
                        },
                        new
                        {
                            PointInterestId = 5,
                            CityId = 5,
                            Description = "La Ciudad Amurallada de Cartagena es un impresionante sitio histórico con calles adoquinadas y encanto colonial.",
                            Name = "Ciudad Amurallada"
                        },
                        new
                        {
                            PointInterestId = 6,
                            CityId = 6,
                            Description = "El Parque Nacional Natural Tayrona es un paraíso natural con playas de arena blanca y exuberante vegetación.",
                            Name = "Parque Nacional Natural Tayrona"
                        },
                        new
                        {
                            PointInterestId = 7,
                            CityId = 7,
                            Description = "La majestuosa Catedral de Manizales se eleva sobre la ciudad y ofrece una vista panorámica de los paisajes circundantes.",
                            Name = "Catedral de Manizales"
                        },
                        new
                        {
                            PointInterestId = 8,
                            CityId = 8,
                            Description = "Los Termales de Santa Rosa de Cabal son aguas termales naturales en medio de la naturaleza, perfectas para relajarse.",
                            Name = "Termales de Santa Rosa de Cabal"
                        },
                        new
                        {
                            PointInterestId = 9,
                            CityId = 9,
                            Description = "La Laguna de la Cocha es un hermoso lago rodeado de montañas y un destino popular para turistas y lugareños.",
                            Name = "Laguna de la Cocha"
                        },
                        new
                        {
                            PointInterestId = 10,
                            CityId = 10,
                            Description = "El Jardín Botánico San Jorge ofrece una colección impresionante de flora y es un oasis de tranquilidad en Ibagué.",
                            Name = "Jardín Botánico San Jorge"
                        },
                        new
                        {
                            PointInterestId = 11,
                            CityId = 11,
                            Description = "El Desierto de la Tatacoa es una formación de paisaje único con cañones y áreas desérticas, perfecto para la observación de estrellas.",
                            Name = "Desierto de la Tatacoa"
                        });
                });

            modelBuilder.Entity("InfoCity.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("InfoCity.API.Entities.City", "City")
                        .WithMany("PointInterests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("InfoCity.API.Entities.City", b =>
                {
                    b.Navigation("PointInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
